version: '3.7'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventmanagement
    ports:
      - "9432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local